### ISSUE TITLE
Create a config based authentication system and a Auth-token system.

### ISSUE THREAD

**Issue by budhajeewa** [a2way-com/athenaeum#1]
There is no need for this application to be multi user. So the setting of login details should be done in config files.

However, we will have to use an Auth-token system to prevent sending username and password over HTTP more than needed, and to facilitate functionalities like expiration of login.

What do you think @randikagit?

**Comment by randikagit** [comment]
@budhajeewa Yeah,That would be great.This is a single user application,Therefore this doesn't need a users table.
